export const GET_USER_START = "GET_USER_START";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_USER_ACTIVE_START = "GET_USER_ACTIVE_START";
export const GET_USER_ACTIVE_SUCCESS = "GET_USER_ACTIVE_SUCCESS";
export const GET_USER_ACTIVE_ERROR = "GET_USER_ACTIVE_ERROR";
