export const SAVE_USER_START = 'SAVE_USER_START';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR';
export const SAVE_USER_SUCCESS_FALSE = 'SAVE_USER_SUCCESS_FALSE';
